version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  python_app:
    build: .
    container_name: python_app
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - .:/app
    restart: "no"  # Контейнер завершит работу после выполнения скрипта

volumes:
  mongodb_data: